version: '3'

services:
  database:
    container_name: database
    restart: always
    image: mongo
    ports:
      - "8080:27017"

  backend:
    container_name: backend
    restart: always
    build: ./Backend
    ports:
      - "5000:4000"
    depends_on:
      - database
    links:
      - database
    
